version: '3.8'

services:
  discord-bot:
    build: .
    container_name: gta-strandmarkt-bot
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    volumes:
      - ./data:/app/data
      - ./strandmarkt.db:/app/strandmarkt.db
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "node", "-e", "process.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3